// This file is auto-generated by scripts/generate-sitemap.ts
// Do not edit by hand.

import type { CatalogListKind } from './types';

export type CatalogLink = { title: string; href: string; category?: string };

export const catalogLinks: Record<CatalogListKind, CatalogLink[]> = {
  "components": [
    {
      "title": "Accordion",
      "href": "/components/accordion"
    },
    {
      "title": "Alerts",
      "href": "/components/alerts"
    },
    {
      "title": "Avatar",
      "href": "/components/avatar"
    },
    {
      "title": "Badge",
      "href": "/components/badge"
    },
    {
      "title": "Breadcrumb",
      "href": "/components/breadcrumb"
    },
    {
      "title": "Button",
      "href": "/components/button"
    },
    {
      "title": "Button Group",
      "href": "/components/button-group"
    },
    {
      "title": "Calendar",
      "href": "/components/calendar"
    },
    {
      "title": "Card",
      "href": "/components/card"
    },
    {
      "title": "Checkbox",
      "href": "/components/checkbox"
    },
    {
      "title": "Collapsible",
      "href": "/components/collapsible"
    },
    {
      "title": "Combobox",
      "href": "/components/combobox"
    },
    {
      "title": "Data Table",
      "href": "/components/data-table"
    },
    {
      "title": "Date Picker",
      "href": "/components/date-picker"
    },
    {
      "title": "Dialog",
      "href": "/components/dialog"
    },
    {
      "title": "Dropdown Menu",
      "href": "/components/dropdown-menu"
    },
    {
      "title": "Form",
      "href": "/components/form"
    },
    {
      "title": "Input Mask",
      "href": "/components/input-mask"
    },
    {
      "title": "Input OTP",
      "href": "/components/input-otp"
    },
    {
      "title": "Pagination",
      "href": "/components/pagination"
    },
    {
      "title": "Popover",
      "href": "/components/popover"
    },
    {
      "title": "Radio Group",
      "href": "/components/radio-group"
    },
    {
      "title": "Select",
      "href": "/components/select"
    },
    {
      "title": "Sheet",
      "href": "/components/sheet"
    },
    {
      "title": "Sonner",
      "href": "/components/sonner"
    },
    {
      "title": "Switch",
      "href": "/components/switch"
    },
    {
      "title": "Table",
      "href": "/components/table"
    },
    {
      "title": "Tabs",
      "href": "/components/tabs"
    },
    {
      "title": "Textarea",
      "href": "/components/textarea"
    },
    {
      "title": "Tooltip",
      "href": "/components/tooltip"
    }
  ],
  "animated-components": [
    {
      "title": "Aave Swap Component",
      "href": "/animated-components/aave-swap-component",
      "category": "micro-interaction"
    },
    {
      "title": "Activities Card",
      "href": "/animated-components/activities-card",
      "category": "disclosure"
    },
    {
      "title": "Adaptive Slider",
      "href": "/animated-components/adaptive-slider",
      "category": "sliders"
    },
    {
      "title": "Add Cash Disclosure",
      "href": "/animated-components/add-cash-disclosure",
      "category": "disclosure"
    },
    {
      "title": "Budget Card",
      "href": "/animated-components/budget-card",
      "category": "cards"
    },
    {
      "title": "Calendar Widget",
      "href": "/animated-components/calendar-widget",
      "category": "widgets"
    },
    {
      "title": "Card Cue",
      "href": "/animated-components/card-cue",
      "category": "micro-interaction"
    },
    {
      "title": "Card Split Accordian",
      "href": "/animated-components/card-split-accordian",
      "category": "accordian"
    },
    {
      "title": "Card Swipe",
      "href": "/animated-components/card-swipe",
      "category": "interaction"
    },
    {
      "title": "Carousel Navigator",
      "href": "/animated-components/carousel-navigator",
      "category": "micro-interaction"
    },
    {
      "title": "Carousel Slider",
      "href": "/animated-components/carousel-slider",
      "category": "interaction"
    },
    {
      "title": "Changeable Pricing Section",
      "href": "/animated-components/changeable-pricing-section",
      "category": "marketing"
    },
    {
      "title": "Collection Grid Disclosure",
      "href": "/animated-components/collection-grid-disclosure",
      "category": "micro-interaction"
    },
    {
      "title": "Command Search",
      "href": "/animated-components/command-search",
      "category": "navigation"
    },
    {
      "title": "Compose Email Card",
      "href": "/animated-components/compose-email-card",
      "category": "cards"
    },
    {
      "title": "Contextual AI Bar",
      "href": "/animated-components/contextual-ai-bar",
      "category": "micro-interaction"
    },
    {
      "title": "Continuous Pagination",
      "href": "/animated-components/continuous-pagination",
      "category": "pagination"
    },
    {
      "title": "Continuous Tabs",
      "href": "/animated-components/continuous-tabs",
      "category": "tabs"
    },
    {
      "title": "Copy Confirm",
      "href": "/animated-components/copy-confirm",
      "category": "micro-interaction"
    },
    {
      "title": "Create Community",
      "href": "/animated-components/create-community",
      "category": "dialog"
    },
    {
      "title": "Create New Disclosure",
      "href": "/animated-components/create-new-disclosure",
      "category": "disclosure"
    },
    {
      "title": "Credit Usage Card",
      "href": "/animated-components/credit-usage-card",
      "category": "cards"
    },
    {
      "title": "Deployment Card",
      "href": "/animated-components/deployment-card",
      "category": "cards"
    },
    {
      "title": "Dialog Stack",
      "href": "/animated-components/dialog-stack",
      "category": "dialog"
    },
    {
      "title": "Discrete Tabs",
      "href": "/animated-components/discrete-tabs",
      "category": "tabs"
    },
    {
      "title": "Dock Component",
      "href": "/animated-components/dock",
      "category": "micro-interaction"
    },
    {
      "title": "Draw Signature",
      "href": "/animated-components/draw-signature",
      "category": "inputs"
    },
    {
      "title": "Dropdown Disclosure",
      "href": "/animated-components/dropdown-disclosure",
      "category": "micro-interaction"
    },
    {
      "title": "Edit Badge",
      "href": "/animated-components/edit-badge",
      "category": "interaction"
    },
    {
      "title": "Edit Profile",
      "href": "/animated-components/edit-profile",
      "category": "dialog"
    },
    {
      "title": "Editable Chip",
      "href": "/animated-components/editable-chip",
      "category": "micro-interaction"
    },
    {
      "title": "Emoji Spree Choice Chips",
      "href": "/animated-components/emoji-spree-choice-chips",
      "category": "choice-chips"
    },
    {
      "title": "Event Reminders",
      "href": "/animated-components/event-reminders",
      "category": "micro-interaction"
    },
    {
      "title": "Expand Details",
      "href": "/animated-components/expand-details",
      "category": "micro-interaction"
    },
    {
      "title": "Expandable Event Card",
      "href": "/animated-components/expandable-event-card",
      "category": "cards"
    },
    {
      "title": "Expandable Profile Card",
      "href": "/animated-components/expandable-profile-card",
      "category": "cards"
    },
    {
      "title": "Extended Toolbar",
      "href": "/animated-components/extended-toolbar",
      "category": "micro-interaction"
    },
    {
      "title": "Family Receive Button",
      "href": "/animated-components/family-receive-button",
      "category": "buttons"
    },
    {
      "title": "Family Wallet",
      "href": "/animated-components/family-wallet",
      "category": "micro-interaction"
    },
    {
      "title": "Feature Tour",
      "href": "/animated-components/feature-tour",
      "category": "micro-interaction"
    },
    {
      "title": "Feedback",
      "href": "/animated-components/feedback",
      "category": "micro-interaction"
    },
    {
      "title": "Feedback Action",
      "href": "/animated-components/feedback-action",
      "category": "micro-interaction"
    },
    {
      "title": "Filter Disclosure",
      "href": "/animated-components/filter-disclosure",
      "category": "filters"
    },
    {
      "title": "Floating Disclosure",
      "href": "/animated-components/floating-disclosure",
      "category": "popover"
    },
    {
      "title": "Floating Input",
      "href": "/animated-components/floating-input",
      "category": "inputs"
    },
    {
      "title": "Fluid Tabs",
      "href": "/animated-components/fluid-tabs",
      "category": "tabs"
    },
    {
      "title": "Fractional Picker",
      "href": "/animated-components/fractional-picker",
      "category": "micro-interaction"
    },
    {
      "title": "Frequency Selector",
      "href": "/animated-components/frequency-selector",
      "category": "tabs"
    },
    {
      "title": "Fund Widget",
      "href": "/animated-components/fund-widget",
      "category": "widgets"
    },
    {
      "title": "Gooey Menu",
      "href": "/animated-components/gooey-menu",
      "category": "tooltip"
    },
    {
      "title": "Inline Action",
      "href": "/animated-components/inline-action",
      "category": "action"
    },
    {
      "title": "Inline Disclosure Menu",
      "href": "/animated-components/inline-disclosure-menu",
      "category": "dropdown"
    },
    {
      "title": "Inline Edit",
      "href": "/animated-components/inline-edit",
      "category": "micro-interaction"
    },
    {
      "title": "Inline Overflow",
      "href": "/animated-components/inline-overflow",
      "category": "disclosure"
    },
    {
      "title": "Inline Table Control",
      "href": "/animated-components/inline-table-control",
      "category": "micro-interaction"
    },
    {
      "title": "Inline Toast",
      "href": "/animated-components/inline-toast",
      "category": "micro-interaction"
    },
    {
      "title": "Integration Card",
      "href": "/animated-components/integration-card",
      "category": "cards"
    },
    {
      "title": "Invite Disclosure",
      "href": "/animated-components/invite-disclosure",
      "category": "disclosure"
    },
    {
      "title": "Journal Navigation",
      "href": "/animated-components/journal-navigation",
      "category": "navigation"
    },
    {
      "title": "Knob Slider",
      "href": "/animated-components/knob-slider",
      "category": "sliders"
    },
    {
      "title": "Labeled Progress Indicator",
      "href": "/animated-components/labeled-progress-indicator",
      "category": "micro-interaction"
    },
    {
      "title": "Layered Progressive Disclosure",
      "href": "/animated-components/layered-progressive-disclosure",
      "category": "interaction"
    },
    {
      "title": "Licence Key",
      "href": "/animated-components/licence-key",
      "category": "micro-interaction"
    },
    {
      "title": "List Stack",
      "href": "/animated-components/list-stack",
      "category": "micro-interaction"
    },
    {
      "title": "macOS Sidebar",
      "href": "/animated-components/macos-sidebar",
      "category": "navigation"
    },
    {
      "title": "Meeting Card",
      "href": "/animated-components/meeting-card",
      "category": "cards"
    },
    {
      "title": "Minimal Carousel",
      "href": "/animated-components/minimal-carousel",
      "category": "carousel"
    },
    {
      "title": "Morphing Button",
      "href": "/animated-components/morphing-button",
      "category": "buttons"
    },
    {
      "title": "Morphing Discovery Bar",
      "href": "/animated-components/morphing-discovery-bar",
      "category": "tabs"
    },
    {
      "title": "Morphing Sidebar Controls",
      "href": "/animated-components/morphing-sidebar-controls",
      "category": "interaction"
    },
    {
      "title": "Onboarding Checklist",
      "href": "/animated-components/onboarding-checklist",
      "category": "cards"
    },
    {
      "title": "Onboarding Screen",
      "href": "/animated-components/onboarding-screen",
      "category": "cards"
    },
    {
      "title": "Onboarding Setup",
      "href": "/animated-components/onboarding-setup",
      "category": "cards"
    },
    {
      "title": "pagination",
      "href": "/animated-components/pagination",
      "category": "pagination"
    },
    {
      "title": "Pin Item",
      "href": "/animated-components/pin-item",
      "category": "lists"
    },
    {
      "title": "Pop Stepper",
      "href": "/animated-components/pop-stepper",
      "category": "micro-interaction"
    },
    {
      "title": "Predictive Text",
      "href": "/animated-components/predictive-text",
      "category": "micro-interaction"
    },
    {
      "title": "Pricing Widget",
      "href": "/animated-components/pricing-widget",
      "category": "widgets"
    },
    {
      "title": "Profile Card",
      "href": "/animated-components/profile-card",
      "category": "cards"
    },
    {
      "title": "Progressive Input Stack",
      "href": "/animated-components/progressive-input-stack",
      "category": "widgets"
    },
    {
      "title": "Quick Feedback",
      "href": "/animated-components/quick-feedback",
      "category": "micro-interaction"
    },
    {
      "title": "Quick Option Picker",
      "href": "/animated-components/quick-option-picker",
      "category": "micro-interaction"
    },
    {
      "title": "Quick Paste",
      "href": "/animated-components/quick-paste",
      "category": "micro-interaction"
    },
    {
      "title": "Quick Switcher",
      "href": "/animated-components/quick-switcher",
      "category": "micro-interaction"
    },
    {
      "title": "Radial Carousel",
      "href": "/animated-components/radial-carousel",
      "category": "carousel"
    },
    {
      "title": "Range Selection Slider",
      "href": "/animated-components/range-selection-slider",
      "category": "widgets"
    },
    {
      "title": "Returns Calculator Snippet",
      "href": "/animated-components/returns-calculator-snippet",
      "category": "cards"
    },
    {
      "title": "Reveal Copy",
      "href": "/animated-components/reveal-copy",
      "category": "micro-interaction"
    },
    {
      "title": "Revealing Cards",
      "href": "/animated-components/revealing-cards",
      "category": "micro-interaction"
    },
    {
      "title": "Run Action Button",
      "href": "/animated-components/run-action-button",
      "category": "buttons"
    },
    {
      "title": "Run Widget",
      "href": "/animated-components/run-widget",
      "category": "widgets"
    },
    {
      "title": "Save Toggle",
      "href": "/animated-components/save-toggle",
      "category": "buttons"
    },
    {
      "title": "Schedule Button",
      "href": "/animated-components/schedule-button",
      "category": "interaction"
    },
    {
      "title": "Schedule Date",
      "href": "/animated-components/schedule-date",
      "category": "scheduler"
    },
    {
      "title": "Scroll Island",
      "href": "/animated-components/scroll-island",
      "category": "micro-interaction"
    },
    {
      "title": "Scrub Slider",
      "href": "/animated-components/scrub-slider",
      "category": "micro-interaction"
    },
    {
      "title": "Select AI Agent",
      "href": "/animated-components/select-ai-agent",
      "category": "micro-interaction"
    },
    {
      "title": "Send Money",
      "href": "/animated-components/send-money",
      "category": "micro-interaction"
    },
    {
      "title": "share sheet",
      "href": "/animated-components/share-sheet",
      "category": "widgets"
    },
    {
      "title": "Shimmer Button",
      "href": "/animated-components/shimmer-button",
      "category": "buttons"
    },
    {
      "title": "Show QR",
      "href": "/animated-components/show-qr",
      "category": "widgets"
    },
    {
      "title": "Shuffle Pinned List",
      "href": "/animated-components/shuffle-pinned-item",
      "category": "lists"
    },
    {
      "title": "Slot Picker",
      "href": "/animated-components/slot-picker",
      "category": "interaction"
    },
    {
      "title": "Split Actions",
      "href": "/animated-components/split-actions",
      "category": "micro-interaction"
    },
    {
      "title": "Split Button",
      "href": "/animated-components/split-button",
      "category": "buttons"
    },
    {
      "title": "Split To edit",
      "href": "/animated-components/split-to-edit",
      "category": "micro-interaction"
    },
    {
      "title": "Status Picker",
      "href": "/animated-components/status-picker",
      "category": "micro-interaction"
    },
    {
      "title": "Step Indicator",
      "href": "/animated-components/step-indicator",
      "category": "micro-interaction"
    },
    {
      "title": "Step Pager",
      "href": "/animated-components/step-pager",
      "category": "micro-interaction"
    },
    {
      "title": "stepper",
      "href": "/animated-components/stepper",
      "category": "buttons"
    },
    {
      "title": "Subscription Calendar",
      "href": "/animated-components/subscription-calendar",
      "category": "cards"
    },
    {
      "title": "Swap Currency Card",
      "href": "/animated-components/swap-currency-card",
      "category": "widgets"
    },
    {
      "title": "Swap Form",
      "href": "/animated-components/swap-form",
      "category": "interaction"
    },
    {
      "title": "Switch Disclosure",
      "href": "/animated-components/switch-disclosure",
      "category": "disclosure"
    },
    {
      "title": "Switch Mode",
      "href": "/animated-components/switch-mode",
      "category": "toggle"
    },
    {
      "title": "Tags",
      "href": "/animated-components/tags",
      "category": "interaction"
    },
    {
      "title": "Task Widget Disclosure",
      "href": "/animated-components/task-widget-disclosure",
      "category": "disclosure"
    },
    {
      "title": "Timed Undo Action",
      "href": "/animated-components/time-undo-action",
      "category": "buttons"
    },
    {
      "title": "Tooltip Navbar",
      "href": "/animated-components/tooltip-navbar",
      "category": "tooltip"
    },
    {
      "title": "Trade Summary",
      "href": "/animated-components/trade-summary",
      "category": "cards"
    },
    {
      "title": "Transaction List",
      "href": "/animated-components/transaction-list",
      "category": "micro-interaction"
    },
    {
      "title": "Tree-menu",
      "href": "/animated-components/tree-menu",
      "category": "navigation"
    },
    {
      "title": "Uniswap Dialog",
      "href": "/animated-components/uniswap-dialog",
      "category": "dialog"
    },
    {
      "title": "Vertical Tooltip Navbar",
      "href": "/animated-components/vertical-tooltip-navbar",
      "category": "tooltip"
    },
    {
      "title": "View On Map",
      "href": "/animated-components/view-on-map",
      "category": "map"
    },
    {
      "title": "Voice Chat Disclosure",
      "href": "/animated-components/voice-chat-disclosure",
      "category": "interaction"
    },
    {
      "title": "Voice Note",
      "href": "/animated-components/voice-note",
      "category": "micro-interaction"
    },
    {
      "title": "Voice Transcribe",
      "href": "/animated-components/voice-transcribe",
      "category": "micro-interaction"
    },
    {
      "title": "Waveform Scrub",
      "href": "/animated-components/waveform-scrub",
      "category": "media"
    },
    {
      "title": "Weight Widget",
      "href": "/animated-components/weight-widget",
      "category": "widgets"
    },
    {
      "title": "Wiggling Cards",
      "href": "/animated-components/wiggling-cards",
      "category": "carousel"
    }
  ],
  "blocks": [
    {
      "title": "Announcement 1",
      "href": "/block/announcement-1",
      "category": "announcement"
    },
    {
      "title": "Announcement 2",
      "href": "/block/announcement-2",
      "category": "announcement"
    },
    {
      "title": "Announcement 3",
      "href": "/block/announcement-3",
      "category": "announcement"
    },
    {
      "title": "Announcement 4",
      "href": "/block/announcement-4",
      "category": "announcement"
    },
    {
      "title": "Announcement 5",
      "href": "/block/announcement-5",
      "category": "announcement"
    },
    {
      "title": "Announcement 6",
      "href": "/block/announcement-6",
      "category": "announcement"
    },
    {
      "title": "Announcement 7",
      "href": "/block/announcement-7",
      "category": "announcement"
    },
    {
      "title": "Announcement 8",
      "href": "/block/announcement-8",
      "category": "announcement"
    },
    {
      "title": "Announcement 9",
      "href": "/block/announcement-9",
      "category": "announcement"
    },
    {
      "title": "auth 01",
      "href": "/block/auth-01",
      "category": "auth"
    },
    {
      "title": "auth 02",
      "href": "/block/auth-02",
      "category": "auth"
    },
    {
      "title": "auth 03",
      "href": "/block/auth-03",
      "category": "auth"
    },
    {
      "title": "auth 04",
      "href": "/block/auth-04",
      "category": "auth"
    },
    {
      "title": "auth 05",
      "href": "/block/auth-05",
      "category": "auth"
    },
    {
      "title": "auth 06",
      "href": "/block/auth-06",
      "category": "auth"
    },
    {
      "title": "auth 07",
      "href": "/block/auth-07",
      "category": "auth"
    },
    {
      "title": "auth 08",
      "href": "/block/auth-08",
      "category": "auth"
    },
    {
      "title": "auth 09",
      "href": "/block/auth-09",
      "category": "auth"
    },
    {
      "title": "auth 10",
      "href": "/block/auth-10",
      "category": "auth"
    },
    {
      "title": "auth 11",
      "href": "/block/auth-11",
      "category": "auth"
    },
    {
      "title": "auth 12",
      "href": "/block/auth-12",
      "category": "auth"
    },
    {
      "title": "auth 13",
      "href": "/block/auth-13",
      "category": "auth"
    },
    {
      "title": "Bento 1",
      "href": "/block/bento-01",
      "category": "bento"
    },
    {
      "title": "Bento 2",
      "href": "/block/bento-02",
      "category": "bento"
    },
    {
      "title": "Blog 1",
      "href": "/block/blog-1",
      "category": "blog"
    },
    {
      "title": "Blog 2",
      "href": "/block/blog-2",
      "category": "blog"
    },
    {
      "title": "Blog 3",
      "href": "/block/blog-3",
      "category": "blog"
    },
    {
      "title": "Blog 4",
      "href": "/block/blog-4",
      "category": "blog"
    },
    {
      "title": "career 1",
      "href": "/block/career-1",
      "category": "career"
    },
    {
      "title": "career 2",
      "href": "/block/career-2",
      "category": "career"
    },
    {
      "title": "career 3",
      "href": "/block/career-3",
      "category": "career"
    },
    {
      "title": "career 4",
      "href": "/block/career-4",
      "category": "career"
    },
    {
      "title": "contact 1",
      "href": "/block/contact-1",
      "category": "contact"
    },
    {
      "title": "contact 2",
      "href": "/block/contact-2",
      "category": "contact"
    },
    {
      "title": "contact 3",
      "href": "/block/contact-3",
      "category": "contact"
    },
    {
      "title": "contact 4",
      "href": "/block/contact-4",
      "category": "contact"
    },
    {
      "title": "contact 5",
      "href": "/block/contact-5",
      "category": "contact"
    },
    {
      "title": "contact 6",
      "href": "/block/contact-6",
      "category": "contact"
    },
    {
      "title": "contact 7",
      "href": "/block/contact-7",
      "category": "contact"
    },
    {
      "title": "cta 1",
      "href": "/block/cta-1",
      "category": "cta"
    },
    {
      "title": "cta 2",
      "href": "/block/cta-2",
      "category": "cta"
    },
    {
      "title": "cta 3",
      "href": "/block/cta-3",
      "category": "cta"
    },
    {
      "title": "cta 4",
      "href": "/block/cta-4",
      "category": "cta"
    },
    {
      "title": "cta 5",
      "href": "/block/cta-5",
      "category": "cta"
    },
    {
      "title": "error 1",
      "href": "/block/error-1",
      "category": "error"
    },
    {
      "title": "error 2",
      "href": "/block/error-2",
      "category": "error"
    },
    {
      "title": "error 3",
      "href": "/block/error-3",
      "category": "error"
    },
    {
      "title": "error 4",
      "href": "/block/error-4",
      "category": "error"
    },
    {
      "title": "error 5",
      "href": "/block/error-5",
      "category": "error"
    },
    {
      "title": "error 6",
      "href": "/block/error-6",
      "category": "error"
    },
    {
      "title": "error 7",
      "href": "/block/error-7",
      "category": "error"
    },
    {
      "title": "faq 1",
      "href": "/block/faq-1",
      "category": "faq"
    },
    {
      "title": "faq 2",
      "href": "/block/faq-2",
      "category": "faq"
    },
    {
      "title": "faq 3",
      "href": "/block/faq-3",
      "category": "faq"
    },
    {
      "title": "faq 4",
      "href": "/block/faq-4",
      "category": "faq"
    },
    {
      "title": "faq 5",
      "href": "/block/faq-5",
      "category": "faq"
    },
    {
      "title": "FAQ 6",
      "href": "/block/faq-6",
      "category": "faq"
    },
    {
      "title": "Feature 1",
      "href": "/block/feature-1",
      "category": "feature"
    },
    {
      "title": "Feature 2",
      "href": "/block/feature-2",
      "category": "feature"
    },
    {
      "title": "Feature 3",
      "href": "/block/feature-3",
      "category": "feature"
    },
    {
      "title": "Feature 4",
      "href": "/block/feature-4",
      "category": "feature"
    },
    {
      "title": "Feature 5",
      "href": "/block/feature-5",
      "category": "feature"
    },
    {
      "title": "file-upload 1",
      "href": "/block/file-upload-1",
      "category": "file-upload"
    },
    {
      "title": "file-upload 2",
      "href": "/block/file-upload-2",
      "category": "file-upload"
    },
    {
      "title": "file-upload 3",
      "href": "/block/file-upload-3",
      "category": "file-upload"
    },
    {
      "title": "file-upload 4",
      "href": "/block/file-upload-4",
      "category": "file-upload"
    },
    {
      "title": "file-upload 5",
      "href": "/block/file-upload-5",
      "category": "file-upload"
    },
    {
      "title": "Footer 1",
      "href": "/block/footer-1",
      "category": "footer"
    },
    {
      "title": "Footer 10",
      "href": "/block/footer-10",
      "category": "footer"
    },
    {
      "title": "Footer 11",
      "href": "/block/footer-11",
      "category": "footer"
    },
    {
      "title": "Footer 12",
      "href": "/block/footer-12",
      "category": "footer"
    },
    {
      "title": "Footer 13",
      "href": "/block/footer-13",
      "category": "footer"
    },
    {
      "title": "Footer 14",
      "href": "/block/footer-14",
      "category": "footer"
    },
    {
      "title": "Footer 15",
      "href": "/block/footer-15",
      "category": "footer"
    },
    {
      "title": "Footer 16",
      "href": "/block/footer-16",
      "category": "footer"
    },
    {
      "title": "Footer 17",
      "href": "/block/footer-17",
      "category": "footer"
    },
    {
      "title": "Footer 18",
      "href": "/block/footer-18",
      "category": "footer"
    },
    {
      "title": "Footer 19",
      "href": "/block/footer-19",
      "category": "footer"
    },
    {
      "title": "Footer 2",
      "href": "/block/footer-2",
      "category": "footer"
    },
    {
      "title": "Footer 20",
      "href": "/block/footer-20",
      "category": "footer"
    },
    {
      "title": "Footer 21",
      "href": "/block/footer-21",
      "category": "footer"
    },
    {
      "title": "Footer 22",
      "href": "/block/footer-22",
      "category": "footer"
    },
    {
      "title": "Footer 23",
      "href": "/block/footer-23",
      "category": "footer"
    },
    {
      "title": "Footer 24",
      "href": "/block/footer-24",
      "category": "footer"
    },
    {
      "title": "Footer 25",
      "href": "/block/footer-25",
      "category": "footer"
    },
    {
      "title": "Footer 26",
      "href": "/block/footer-26",
      "category": "footer"
    },
    {
      "title": "Footer 27",
      "href": "/block/footer-27",
      "category": "footer"
    },
    {
      "title": "Footer 28",
      "href": "/block/footer-28",
      "category": "footer"
    },
    {
      "title": "Footer 29",
      "href": "/block/footer-29",
      "category": "footer"
    },
    {
      "title": "Footer 3",
      "href": "/block/footer-3",
      "category": "footer"
    },
    {
      "title": "Footer 30",
      "href": "/block/footer-30",
      "category": "footer"
    },
    {
      "title": "Footer 31",
      "href": "/block/footer-31",
      "category": "footer"
    },
    {
      "title": "Footer 4",
      "href": "/block/footer-4",
      "category": "footer"
    },
    {
      "title": "Footer 5",
      "href": "/block/footer-5",
      "category": "footer"
    },
    {
      "title": "Footer 6",
      "href": "/block/footer-6",
      "category": "footer"
    },
    {
      "title": "Footer 7",
      "href": "/block/footer-7",
      "category": "footer"
    },
    {
      "title": "Footer 8",
      "href": "/block/footer-8",
      "category": "footer"
    },
    {
      "title": "Footer 9",
      "href": "/block/footer-9",
      "category": "footer"
    },
    {
      "title": "hero 1",
      "href": "/block/hero-1",
      "category": "hero"
    },
    {
      "title": "hero 10",
      "href": "/block/hero-10",
      "category": "hero"
    },
    {
      "title": "hero 11",
      "href": "/block/hero-11",
      "category": "hero"
    },
    {
      "title": "hero 12",
      "href": "/block/hero-12",
      "category": "hero"
    },
    {
      "title": "hero 13",
      "href": "/block/hero-13",
      "category": "hero"
    },
    {
      "title": "hero 14",
      "href": "/block/hero-14",
      "category": "hero"
    },
    {
      "title": "hero 15",
      "href": "/block/hero-15",
      "category": "hero"
    },
    {
      "title": "hero 16",
      "href": "/block/hero-16",
      "category": "hero"
    },
    {
      "title": "hero 17",
      "href": "/block/hero-17",
      "category": "hero"
    },
    {
      "title": "hero 18",
      "href": "/block/hero-18",
      "category": "hero"
    },
    {
      "title": "hero 19",
      "href": "/block/hero-19",
      "category": "hero"
    },
    {
      "title": "hero 2",
      "href": "/block/hero-2",
      "category": "hero"
    },
    {
      "title": "hero 20",
      "href": "/block/hero-20",
      "category": "hero"
    },
    {
      "title": "hero 21",
      "href": "/block/hero-21",
      "category": "hero"
    },
    {
      "title": "hero 22",
      "href": "/block/hero-22",
      "category": "hero"
    },
    {
      "title": "hero 23",
      "href": "/block/hero-23",
      "category": "hero"
    },
    {
      "title": "hero 24",
      "href": "/block/hero-24",
      "category": "hero"
    },
    {
      "title": "hero 25",
      "href": "/block/hero-25",
      "category": "hero"
    },
    {
      "title": "hero 26",
      "href": "/block/hero-26",
      "category": "hero"
    },
    {
      "title": "hero 27",
      "href": "/block/hero-27",
      "category": "hero"
    },
    {
      "title": "hero 28",
      "href": "/block/hero-28",
      "category": "hero"
    },
    {
      "title": "hero 29",
      "href": "/block/hero-29",
      "category": "hero"
    },
    {
      "title": "hero 3",
      "href": "/block/hero-3",
      "category": "hero"
    },
    {
      "title": "hero 30",
      "href": "/block/hero-30",
      "category": "hero"
    },
    {
      "title": "Hero 31",
      "href": "/block/hero-31",
      "category": "hero"
    },
    {
      "title": "Hero 32",
      "href": "/block/hero-32",
      "category": "hero"
    },
    {
      "title": "Hero 33",
      "href": "/block/hero-33",
      "category": "hero"
    },
    {
      "title": "Hero 34",
      "href": "/block/hero-34",
      "category": "hero"
    },
    {
      "title": "Hero 35",
      "href": "/block/hero-35",
      "category": "hero"
    },
    {
      "title": "Hero 36",
      "href": "/block/hero-36",
      "category": "hero"
    },
    {
      "title": "Hero 37",
      "href": "/block/hero-37",
      "category": "hero"
    },
    {
      "title": "Hero 38",
      "href": "/block/hero-38",
      "category": "hero"
    },
    {
      "title": "Hero 39",
      "href": "/block/hero-39",
      "category": "hero"
    },
    {
      "title": "hero 4",
      "href": "/block/hero-4",
      "category": "hero"
    },
    {
      "title": "Hero 40",
      "href": "/block/hero-40",
      "category": "hero"
    },
    {
      "title": "Hero 41",
      "href": "/block/hero-41",
      "category": "hero"
    },
    {
      "title": "Hero 42",
      "href": "/block/hero-42",
      "category": "hero"
    },
    {
      "title": "Hero 43",
      "href": "/block/hero-43",
      "category": "hero"
    },
    {
      "title": "hero 5",
      "href": "/block/hero-5",
      "category": "hero"
    },
    {
      "title": "hero 6",
      "href": "/block/hero-6",
      "category": "hero"
    },
    {
      "title": "hero 7",
      "href": "/block/hero-7",
      "category": "hero"
    },
    {
      "title": "hero 8",
      "href": "/block/hero-8",
      "category": "hero"
    },
    {
      "title": "hero 9",
      "href": "/block/hero-9",
      "category": "hero"
    },
    {
      "title": "integrations 1",
      "href": "/block/integrations-1",
      "category": "integrations"
    },
    {
      "title": "integrations 2",
      "href": "/block/integrations-2",
      "category": "integrations"
    },
    {
      "title": "integrations 3",
      "href": "/block/integrations-3",
      "category": "integrations"
    },
    {
      "title": "integrations 4",
      "href": "/block/integrations-4",
      "category": "integrations"
    },
    {
      "title": "integrations 5",
      "href": "/block/integrations-5",
      "category": "integrations"
    },
    {
      "title": "Navigation-1",
      "href": "/block/navigation-1",
      "category": "navigation"
    },
    {
      "title": "Navigation-2",
      "href": "/block/navigation-2",
      "category": "navigation"
    },
    {
      "title": "Navigation-3",
      "href": "/block/navigation-3",
      "category": "navigation"
    },
    {
      "title": "Navigation-4",
      "href": "/block/navigation-4",
      "category": "navigation"
    },
    {
      "title": "Navigation-5",
      "href": "/block/navigation-5",
      "category": "navigation"
    },
    {
      "title": "Navigation-6",
      "href": "/block/navigation-6",
      "category": "navigation"
    },
    {
      "title": "Navigation-7",
      "href": "/block/navigation-7",
      "category": "navigation"
    },
    {
      "title": "newsletter 1",
      "href": "/block/newsletter-1",
      "category": "newsletter"
    },
    {
      "title": "newsletter 2",
      "href": "/block/newsletter-2",
      "category": "newsletter"
    },
    {
      "title": "newsletter 3",
      "href": "/block/newsletter-3",
      "category": "newsletter"
    },
    {
      "title": "newsletter 4",
      "href": "/block/newsletter-4",
      "category": "newsletter"
    },
    {
      "title": "newsletter 5",
      "href": "/block/newsletter-5",
      "category": "newsletter"
    },
    {
      "title": "notification 1",
      "href": "/block/notification-1",
      "category": "notification"
    },
    {
      "title": "notification 2",
      "href": "/block/notification-2",
      "category": "notification"
    },
    {
      "title": "notification 3",
      "href": "/block/notification-3",
      "category": "notification"
    },
    {
      "title": "notification 4",
      "href": "/block/notification-4",
      "category": "notification"
    },
    {
      "title": "Pricing 1",
      "href": "/block/pricing-1",
      "category": "pricing"
    },
    {
      "title": "Pricing 2",
      "href": "/block/pricing-2",
      "category": "pricing"
    },
    {
      "title": "Pricing 3",
      "href": "/block/pricing-3",
      "category": "pricing"
    },
    {
      "title": "Pricing 4",
      "href": "/block/pricing-4",
      "category": "pricing"
    },
    {
      "title": "Pricing 5",
      "href": "/block/pricing-5",
      "category": "pricing"
    },
    {
      "title": "Stats 1",
      "href": "/block/stats-1",
      "category": "stats"
    },
    {
      "title": "Stats 2",
      "href": "/block/stats-2",
      "category": "stats"
    },
    {
      "title": "Stats 3",
      "href": "/block/stats-3",
      "category": "stats"
    },
    {
      "title": "Stats 4",
      "href": "/block/stats-4",
      "category": "stats"
    },
    {
      "title": "Team 1",
      "href": "/block/team-1",
      "category": "team"
    },
    {
      "title": "Team 2",
      "href": "/block/team-2",
      "category": "team"
    },
    {
      "title": "Team 3",
      "href": "/block/team-3",
      "category": "team"
    },
    {
      "title": "Team 4",
      "href": "/block/team-4",
      "category": "team"
    },
    {
      "title": "Team 5",
      "href": "/block/team-5",
      "category": "team"
    },
    {
      "title": "testimonials 1",
      "href": "/block/testimonials-1",
      "category": "testimonials"
    },
    {
      "title": "testimonials 2",
      "href": "/block/testimonials-2",
      "category": "testimonials"
    },
    {
      "title": "testimonials 3",
      "href": "/block/testimonials-3",
      "category": "testimonials"
    },
    {
      "title": "testimonials 4",
      "href": "/block/testimonials-4",
      "category": "testimonials"
    },
    {
      "title": "widget 1",
      "href": "/block/widget-1",
      "category": "widget"
    },
    {
      "title": "widget 2",
      "href": "/block/widget-2",
      "category": "widget"
    },
    {
      "title": "widget 3",
      "href": "/block/widget-3",
      "category": "widget"
    },
    {
      "title": "widget 4",
      "href": "/block/widget-4",
      "category": "widget"
    },
    {
      "title": "widget 5",
      "href": "/block/widget-5",
      "category": "widget"
    },
    {
      "title": "widget 6",
      "href": "/block/widget-6",
      "category": "widget"
    },
    {
      "title": "widget 7",
      "href": "/block/widget-7",
      "category": "widget"
    },
    {
      "title": "widget 8",
      "href": "/block/widget-8",
      "category": "widget"
    },
    {
      "title": "widget 9",
      "href": "/block/widget-9",
      "category": "widget"
    }
  ],
  "dashboards": [
    {
      "title": "Agndex Dashboard",
      "href": "/dashboard/agndex-dashboard"
    },
    {
      "title": "Astrix Dashboard",
      "href": "/dashboard/astrix-dashboard"
    },
    {
      "title": "Bionis Dashboard",
      "href": "/dashboard/bionis-dashboard"
    },
    {
      "title": "Capitalio Dashboard",
      "href": "/dashboard/capitalio-dashboard"
    },
    {
      "title": "Demostack Dashboard",
      "href": "/dashboard/demostack-dashboard"
    },
    {
      "title": "Gridline Dashboard",
      "href": "/dashboard/gridline-dashboard"
    },
    {
      "title": "Jobtracker Dashboard",
      "href": "/dashboard/jobtracker-dashboard"
    },
    {
      "title": "Library Dashboard",
      "href": "/dashboard/library-dashboard"
    },
    {
      "title": "Medesk Dashboard",
      "href": "/dashboard/medesk-dashboard"
    },
    {
      "title": "portfolio Dashboard",
      "href": "/dashboard/portfolio-dashboard"
    },
    {
      "title": "Tallie Dashboard",
      "href": "/dashboard/tallie-dashboard"
    },
    {
      "title": "Web3 Dashboard",
      "href": "/dashboard/web3-dashboard"
    }
  ],
  "templates": [
    {
      "title": "Landing Page 01",
      "href": "/template/landing-01"
    }
  ],
  "showcases": [
    {
      "title": "Product Waitlist Funnel",
      "href": "/showcase/product-waitlist-funnel"
    },
    {
      "title": "SaaS Launch Stack",
      "href": "/showcase/saas-launch-stack"
    }
  ]
};
